name: formation_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: any
  provider: ^6.0.0
  dio: 5.9.0
  retrofit: 4.7.3
  json_annotation: 4.9.0

  # UI
  flutter_svg: 2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  retrofit_generator: 10.0.6
  json_serializable: any
  build_runner: 2.9.0

flutter:

  uses-material-design: true

  assets:
    - res/drawables/
    - res/svg/

  fonts:
    - family: AppIcons
      fonts:
        - asset: res/fonts/app_icons.ttf
    - family: Avenir
      fonts:
        - asset: res/fonts/Avenir-Light.ttf
          weight: 300
        - asset: res/fonts/Avenir-Regular.ttf
          weight: 400
        - asset: res/fonts/Avenir-Medium.ttf
          weight: 500
        - asset: res/fonts/Avenir-Black.ttf
          weight: 900

  generate: true